# This file was generated by GoReleaser. DO NOT EDIT.
cask "ha-client" do
  name "ha-client"
  desc "kubectl-style CLI for Home Assistant"
  homepage "https://github.com/rnorth/ha-client"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ha-client"

  on_macos do
    on_intel do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "92311d7fe0f16f5f7c31a7a64d538b5555a2efa030d94511460fd53973189746"
    end
    on_arm do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "b61154c9d869ae5b3e29a78102ab951c52af5ca3a06f99ec115ebfc2865ce572"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "248f4062d9110cd8786b6bdd6e718208e7054af248832b0b43c71365ac74f5c1"
    end
    on_arm do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "551ac8ce382e87fffdaf6bb220e7908648529722a2c239c51395844c6537e9da"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ha-client"]
    end
  end

  # No zap stanza required
end
