# This file was generated by GoReleaser. DO NOT EDIT.
cask "ha-client" do
  name "ha-client"
  desc "kubectl-style CLI for Home Assistant"
  homepage "https://github.com/rnorth/ha-client"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ha-client"

  on_macos do
    on_intel do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "35d87c452f09b757400f7553040c62dc857df435c195838d30872aff6f8b9517"
    end
    on_arm do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "d72afe2932cfc3b03b45a4bba0996d76cbcf254fc0ac40dd73ac665f4eb7a84c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "05dab85f6ed56f19c0d9ad6963a6dd9e9173eee2cbca1b4e1bcd7b5deae7d333"
    end
    on_arm do
      url "https://github.com/rnorth/ha-client/releases/download/v#{version}/ha-client_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rnorth/ha-client"
      sha256 "53e8b57ffcbb58c6c32f31fe7ca9b81be07911001a61fa94e065f27ad30510a5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ha-client"]
    end
  end

  # No zap stanza required
end
