# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HaClient < Formula
  desc "kubectl-style CLI for Home Assistant"
  homepage "https://github.com/rnorth/ha-client"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnorth/ha-client/releases/download/v0.1.0/ha-client_0.1.0_darwin_amd64.tar.gz"
      sha256 "b54549bcf5ea524a6f2e7c6e22863e4c2cfa1b346491b853c669650eec78c5c3"

      def install
        bin.install "ha-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnorth/ha-client/releases/download/v0.1.0/ha-client_0.1.0_darwin_arm64.tar.gz"
      sha256 "417c4dccad5081a9ab5b6c729c0d716c218c44f88aec1c2bc596e7654a123817"

      def install
        bin.install "ha-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnorth/ha-client/releases/download/v0.1.0/ha-client_0.1.0_linux_amd64.tar.gz"
      sha256 "2943194d8d961c0daa6f6d9000fe53c8c22d518fe4424320b05ca3d5675f9890"
      def install
        bin.install "ha-client"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnorth/ha-client/releases/download/v0.1.0/ha-client_0.1.0_linux_arm64.tar.gz"
      sha256 "57dc48a967173d75264432b5098eb1d4ae07aa5fd2c770b06118aa98e03a8d1a"
      def install
        bin.install "ha-client"
      end
    end
  end
end
