# This formula is auto-generated by GoReleaser on each tagged release.
# See: https://github.com/rnorth/ha-client
class HaClient < Formula
  desc "kubectl-style CLI for Home Assistant"
  homepage "https://github.com/rnorth/ha-client"
  version "0.0.0"

  def install
    # placeholder — replaced by GoReleaser on release
  end
end
